# Generated by Django 2.2.3 on 2019-10-07 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('url', models.CharField(db_index=True, max_length=256, unique=True)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('production_set', models.BooleanField(default=False)),
                ('production_wh', models.CharField(max_length=256, null=True)),
                ('development_wh', models.CharField(max_length=256, null=True)),
                ('actual_webhook', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(db_index=True, max_length=32)),
                ('nombre', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('last_name', models.CharField(db_index=True, max_length=256)),
                ('phone', models.CharField(db_index=True, max_length=25, null=True, unique=True)),
                ('last_chat_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('actual_command_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPrimaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, null=True)),
                ('apellido', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(db_index=True, max_length=14, unique=True)),
                ('mesa', models.CharField(db_index=True, max_length=32, null=True)),
                ('votos_gonzalo', models.IntegerField(db_index=True, default=0)),
                ('votos_leonel', models.IntegerField(db_index=True, default=0)),
                ('acta_imag', models.ImageField(null=True, upload_to='static/building/images/actas/')),
                ('photo_url', models.CharField(max_length=256)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreapp.Municipio')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreapp.TelegramUser')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Provincia'),
        ),
    ]
